# Generated by Django 5.1.1 on 2024-10-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_inventario', models.CharField(max_length=10, unique=True)),
                ('denominacao', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=10)),
                ('link_imagem', models.URLField(blank=True, max_length=500, null=True)),
                ('sala', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=30, unique=True)),
                ('descricao', models.TextField(max_length=1500)),
                ('localizacao', models.CharField(max_length=10)),
                ('link_imagem', models.URLField(blank=True, max_length=500, null=True)),
                ('responsavel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Senai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1500)),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
    ]
