# Generated by Django 5.1.1 on 2024-10-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGDP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='quantidade_itens',
            field=models.IntegerField(default=0),
        ),
    ]
