# Generated by Django 5.1.1 on 2024-10-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGDP', '0003_inventario_responsavel_alter_sala_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
