# Generated by Django 5.1.1 on 2024-11-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGDP', '0004_sala_email_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='status_localizacao',
            field=models.CharField(choices=[('localizado', 'Localizado'), ('nao_localizado', 'Não Localizado')], default='nao_localizado', max_length=15),
        ),
    ]
