# Generated by Django 5.1.1 on 2024-11-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppGDP', '0005_inventario_status_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='status_localizacao',
            field=models.CharField(choices=[('localizado', 'Localizado'), ('não-localizado', 'Não Localizado')], default='não-localizado', max_length=15),
        ),
    ]
